version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-lab"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1kehcwwoefxrb"
s3_prefix = "serverless-lab"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

